const projectsLinks = [
  {
    title: 'Multimodal Chatbot',
    href: '/projects/chatbot',
    isNew: true,
  },
  {
    title: 'YOLO-World',
    href: '/projects/project6',
  },
  {
    title: 'Website generated by Opus 5',
    href: '/projects/project7',
  },
  {
    title: 'Inventaris',
    href: '/projects/project3',
  },
  {
    title: 'SkillMatch',
    href: '/projects/project4',
  },
  {
    title: 'Courtline',
    href: '/projects/project5',
  },
];
export default projectsLinks;
