const projects = [
  {
    id: 'chatbot',
    title: 'Multimodal Chatbot',
    img: '/project-chatbot/project-chatbot.webp',
    link: '/projects/chatbot',
    date: '2026',
    liveLink: '/projects/chatbot',
    company: 'Demo',
    primary: '#141416',
    accentColor: '#f0f4f1',
    secondary: '#f0f4f1',
    fillColor: '#C6FF3D',
    menuColor: '#C6FF3D',
    menuFontColor: '#141416',
    fluidColor: '#C6FF3D',
    images: [
      {
        src: '/project-chatbot/1.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'An interactive multimodal chatbot built into this portfolio template: text, images, MP4 video, and documents with streaming AI responses.',
      'Powered by NVIDIA Nemotron Omni with an optional OpenRouter multimodal fallback. Session memory stays in the browser — no login, with a 30-minute media purge.',
      'Toggle model thinking traces, regenerate answers, and keep chatting in one focused full-page experience.',
    ],
  },
  {
    id: 'project5',
    title: 'Motion Studio',
    img: '/project5/project5.webp',
    link: '/projects/project5',
    date: '2026',
    company: 'Sample',
    liveLink: 'https://example.com',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#FAFAFA',
    fillColor: '#f2f2f2',
    menuColor: '#FFD54F',
    menuFontColor: '#000000',
    fluidColor: '#002AB0',
    images: [
      {
        src: '/project5/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/4.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/5.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'A sample motion-design project showcasing animation, interaction, and modern web composition.',
      'Built to demonstrate how GSAP-driven transitions and scroll choreography can shape a portfolio case study.',
      'Replace this copy and imagery with your own project when you fork the template.',
    ],
  },
  {
    id: 'project7',
    title: 'Product Landing',
    img: '/project7/project7.webp',
    link: '/projects/project7',
    date: '2026',
    company: 'Sample',
    liveLink: 'https://example.com',
    primary: '#050505',
    accentColor: '#f0f4f1',
    secondary: '#f0f4f1',
    fillColor: '#C6FF3D',
    menuColor: '#C6FF3D',
    menuFontColor: '#050505',
    fluidColor: '#C6FF3D',
    images: [
      {
        src: '/project7/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project7/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project7/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project7/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'A fictional product landing page with OLED-dark styling, accent typography, and scroll-driven reveals.',
      'Use this slot for a marketing site, SaaS launch page, or any front-end case study you want to highlight.',
      'All links and copy are placeholders — customize them after cloning.',
    ],
  },
  {
    id: 'project3',
    title: 'Admin Dashboard',
    img: '/project3/project3.webp',
    link: '/projects/project3',
    date: '2026',
    liveLink: 'https://example.com',
    company: 'Sample',
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/project3/9.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/10.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/11.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/12.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project3/1.webp',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'A sample admin dashboard case study with role-based access patterns, data tables, and activity views.',
      'Demonstrates how full-bleed project imagery and long-form descriptions fit the template layout.',
      'Swap screenshots and narrative for your own backend or full-stack work.',
    ],
  },
];
export default projects;
